### PR TITLE
Config option to check remote URLs for blacklisted keywords (rebased, needs testing)

### PR DESCRIPTION
**Pull request by Lamby777**
From https://github.com/jiriks74/presence.nvim/pull/4#issuecomment-2044691003

### CODE REVIEW

**Comment by jiriks74** [comment]
Well sadly I am not able to push changes - Github is weird.

But formatting using `stylua .` should be enough to get rid of the formatting issues. If you look at [the output](https://github.com/jiriks74/presence.nvim/actions/runs/8627441331/job/23656164067?pr=41) of LuaCheck there's some extra argument that is not needed so just get rid of it.

I tried to make these changes myself for half an hour but it seems like Github won't let me access that branch for whatever reason.

**Comment by jiriks74** [comment]
Ok. I, somehow, managed to modify it manually through Github UI. Doing it through git is broken...

**Comment by jiriks74** [comment]
I have no idea what the problem with LuaCheck is

**Comment by jiriks74** [comment]
Turns out that LuaCheck was right and I just don't know Lua well

**Comment by jiriks74** [comment]
Could you please test this now that the PR is up to date and passing? @Lamby777

**Comment by jiriks74** [comment]
For tracking with OpenProject:

[48] Config option to check git remote URLs for blacklisted keywords
https://openproject.stefka.eu/work_packages/48

**Comment by Lamby777** [comment]
> Could you please test this now that the PR is up to date and passing? @Lamby777

Sure, next time I get on the other laptop

**Comment by Lamby777** [comment]
Works fine. Added Lamby777 to the blacklist and it wouldn't show the presence when I opened my game, and then I opened a different project under my org and it showed up.

Off-topic, but you might want to know: the discord application's name is presence.nvim, where the original is Neovim. It looks kinda off seeing the game called `presence.nvim` in the profile instead of Neovim. Easily solved by using the upstream repo's app ID listed in the readme but yea.

**Comment by jiriks74** [comment]
@Lamby777 I named the application in Discord's developer portal as `presence.nvim` and didn't realize that it would name it like that in Rich presence. It's fixed now.

**Comment by jiriks74** [comment]
Also AFAIK this is ready to be merged. I'll test it on the weekend myself to be sure and I'll merge it. Feel free to have any input.

**Comment by Lamby777** [comment]
sounds good

> Feel free to have any input.

The input in question:
:3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3 :3

**Comment by jiriks74** [comment]
I'm sorry for taking longer. I'm finally, hopefully, figuring out what's wrong with my dGPU and I have some school to deal with. I'll do my best to test it before I send the laptop for, *another*, RMA.

**Comment by jiriks74** [comment]
Hey there. Sorry, life's been harder than I anticipated. Everything looks fine so I'll merge it.

**Comment by Lamby777** [comment]
no worries, I was loading this branch of the plugin anyway

**Pull request merged**
