### PR TITLE
Add basic terminal support

### PR DESCRIPTION
**Pull request by jiriks74**

### CODE REVIEW

**Comment by jiriks74** [comment]
@IogaMaster why are you deleting this?

**Comment by IogaMaster** [comment]
I deleted my fork of presence, because I made a new one that I'm developing called neocord.

**Comment by jiriks74** [comment]
Well I currently started going through all the PRs and merging them into the code base. I also added support for Flatpak version of Discord (no workarounds needed). I think that I'll be able to maintain this one or merge people's PRs at the very least. I plan to go through the whole codebase and split it so that it's easier to read and maintain.

Do you still have the patch laying around somewhere? I'd like to take a look at it (I haven't got to this one yet) and potentially merge it.

**Comment by jiriks74** [comment]
I also added some things to make development easier:
- StyLua CI/CD (so that people won't randomly format a file making diffs unreadable - #3)
- I also added a clause to the [README](https://github.com/jiriks74/presence.nvim#contributing) so that people use the same commit messages (better readability, works with parsers, etc.)

**Comment by IogaMaster** [comment]
Are you working on your own fork of the project that won't be merged. Or would this be a contribution?

I don't have a patch but I could re make it.

**Comment by jiriks74** [comment]
> Are you working on your own fork of the project that won't be merged. Or would this be a contribution?
> 
> I don't have a patch but I could re make it.

I'm currently maintaining a fork as the upstream repo seems dead. If it comes back to life I'd either create a PR to update it or join maintainership (if possible) but most likely I'll be maintaining this fork as my own.

If somebody wants to join I'll be glad to add them as long as there won't be a mess/lack of communication when making substantial changes.

**Comment by IogaMaster** [comment]
@jiriks74 Here is the patch.

https://github.com/jiriks74/presence.nvim/commit/df9db96cf406ddc56fb84260c70a856781749bc1.patch

**Comment by jiriks74** [comment]
Thanks a lot. I'll look into it and if there aren't any issues (I doubt there will be) I'll be merging it soon.

**Comment by jiriks74** [comment]
So `git apply` is mad at me so I'll have to patch it myself

**Comment by jiriks74** [comment]
[52] Add basic terminal support

https://openproject.stefka.eu/work_packages/52

**Pull request closed without merging**
